# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f2f19bc13c9ac9e6d9b9fe81dbc3af81e04381dcb6cd979fd695d29127e5f787b1890f58db854dfeb953bb8acfe9dd5dce9a44cf3b2e77bd175e244743c0d6a

test:
  secret_key_base: 7a871116f8b911d22bd6271a14757dbf198c92572eee7edf2fbfc595b67d832e22f9d62444fa5c339a32bcc004eb078ccc12cad41b30acb3c16399644dee6e45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
